name: elastic_client
description: >
  Dart bindings for ElasticSearch HTTP API.
  ElasticSearch is a full-text search engine based on Lucene.
version: 0.2.0-dev
homepage: https://github.com/isoos/elastic_client

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  http: ^0.12.2
  http_client: ^1.0.0
  meta: ^1.0.0

dev_dependencies:
  docker_process: ^1.2.0
  pedantic: ^1.0.0
  test: ^1.0.0
