name: elastic_client
description: >
  Dart bindings for ElasticSearch HTTP API.
  ElasticSearch is a full-text search engine based on Lucene.
version: 0.1.3
homepage: https://github.com/isoos/elastic_client
author: Istvan Soos <istvan.soos@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  http_client: ^1.0.0

dev_dependencies:
  test: ^1.0.0
